version: '3.9'

services:
  api:
    build:
      context: ./api
    container_name: expense-tracker-api
    restart: unless-stopped
    ports:
      - '3096:3000' # NestJS w kontenerze 3000, host 3096
    env_file:
      - ./api/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/expense-tracker
    depends_on:
      - mongo
    command: npm run start:dev
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - expense-network

  frontend:
    build:
      context: ./frontend
    container_name: expense-tracker-frontend
    restart: unless-stopped
    ports:
      - '3000:3000' # React frontend
    environment:
      - CHOKIDAR_USEPOLLING=true # przydatne do watch mode w Dockerze
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - expense-network

  mongo:
    image: mongo:6
    container_name: expense-tracker-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - expense-network

volumes:
  mongo-data:

networks:
  expense-network:
    driver: bridge